import base64
import tempfile
from pathlib import Path
import streamlit as st
from dotenv import load_dotenv
from gtts import gTTS
from agents.root.agent import root_agent as full_story_agent
from adk_runner import run_agent
from io import BytesIO
from utils.media_utils import ( image_to_base64, make_audio, make_audio_base64)
from utils.ui_utils import apply_css
from components.header import render_header
from components.sidebar import render_settings
from components.hero import render_hero
st.set_page_config(page_title="WonderMe", page_icon="⭐", layout="wide")
import time

load_dotenv()
BASE_DIR = Path(__file__).resolve().parent
#LUNA_IMAGE = BASE_DIR / "assets" / "luna2.png"
#luna_img = image_to_base64(LUNA_IMAGE)

CHARACTER_IMAGES = {
    "🐉 Luna the Dragon": BASE_DIR / "assets" / "luna2.png",
    "🤖 Milo the Robot": BASE_DIR / "assets" / "milo.png",
    "🐰 Bella the Bunny": BASE_DIR / "assets" / "bella.png",
    "🐘 Ellie the Elephant": BASE_DIR / "assets" / "elephant.png",
    "🦄 Unico the Unicorn": BASE_DIR / "assets" / "unicorn.png",
    "🐜 Tini the Ant": BASE_DIR / "assets" / "ant.png",
    "🐙 Ollie the Octopus": BASE_DIR / "assets" / "octopus.png",
    "🦆 Ducky the Duck": BASE_DIR / "assets" / "duck.png",
}


def render_audio_on_image(story: str):
    audio_output = make_audio(story)    
    # Handle string path, BytesIO, or raw bytes
    if isinstance(audio_output, str):
        with open(audio_output, "rb") as f:
            audio_bytes = f.read()
    elif hasattr(audio_output, "read"):
        audio_bytes = audio_output.read()
    else:
        audio_bytes = audio_output

    audio_b64 = base64.b64encode(audio_bytes).decode("utf-8")
    st.markdown(
    f"""
        <div style="
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            background: rgba(255, 255, 255, 0.92);
            backdrop-filter: blur(6px);
            padding: 10px 16px;
            border-radius: 0 0 16px 16px;
        ">
            <p style="margin: 0 0 6px 0;">🔊<strong>Listen</strong>
            <audio controls style="width: 100%;">
                <source src="data:audio/mpeg;base64,{audio_b64}" type="audio/mpeg">
            </audio>
            </p>
        </div>
    
    """,
    unsafe_allow_html=True,
)

def render_transcript(story: str):
    st.markdown(
        f"""
        <div class="transcript-card">
            <div class="story-title">📖 Story Transcript : </div>
            <div style="margin-top: 12px; line-height: 1.7; color: #333;">
                {story.replace(chr(10), '<br>')}
            </div>
            <div style="
                margin-top: 16px;
                background: #d4edda;
                border-left: 4px solid #28a745;
                padding: 10px 14px;
                border-radius: 6px;
                color: #155724;
                font-size: 0.9rem;
            ">
                ✅ Generated by Story Agent and reviewed by Safety Agent.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )



#apply_css(luna_img)


render_header()
st.write("")
main_col, side_col = st.columns([3, 1.05])
with side_col:
    age, character, theme, generate, clear, about = render_settings()

selected_image = CHARACTER_IMAGES.get(
    character,
    BASE_DIR / "assets" / "luna2.png"   # fallback image
)

character_img = image_to_base64(selected_image)
apply_css(character_img)


with main_col:
    if "story" not in st.session_state:
        st.session_state.story = ""
    if clear:
        st.session_state.story = ""
    render_hero()

    if generate:
        
        clean_character = character.split(" ", 1)[1]
        prompt = f"""
                Create a story for a child.
                Child age: {age}
                Character: {clean_character}
                Theme: {theme}
                Generate a warm, positive, child-safe story.
                Include a title and a short moral.
                """

        with st.spinner("Creating magical story with ADK agents..."):

            st.session_state.story = run_agent(
                full_story_agent,
                prompt,
                session_id="full_story",
            )

    if st.session_state.story:
        with st.spinner("Preparing audio narration and transcript..."):
            render_audio_on_image(st.session_state.story)
            render_transcript(st.session_state.story)   