import streamlit as st


def render_transcript(story: str) -> None:

    st.markdown(
        f"""
        <div class="transcript-card">

            <div class="story-title">
                📖 Story Transcript
            </div>

            <div style="
                margin-top:12px;
                line-height:1.7;
                color:#333;
            ">
                {story.replace(chr(10), '<br>')}
            </div>

            <div style="
                margin-top:16px;
                background:#d4edda;
                border-left:4px solid #28a745;
                padding:10px 14px;
                border-radius:6px;
                color:#155724;
                font-size:0.9rem;
            ">
                ✅ Generated by Story Agent and reviewed by Safety Agent.
            </div>

        </div>
        """,
        unsafe_allow_html=True,
    )